-- SK60 RNAV flight plan. Generated by nav_system.lua.
-- Edit the waypoints table before a mission to pre-program/shared routes.
-- Columns: FRQ = VOR frequency (MHz), RAD = radial (degrees), DST = distance (NM).

local waypoints = {
    -- WPT   FRQ      RAD    DST
    [ 1] = { FRQ = 112.50, RAD = 153, DST =   0.0 },
    [ 2] = { FRQ = 113.60, RAD =  46, DST =   8.8 },
    [ 3] = { FRQ = 113.60, RAD = 292, DST =  36.9 },
    [ 4] = { FRQ = 109.75, RAD =  12, DST =  25.7 },
    [ 5] = { FRQ = 108.90, RAD = 355, DST =  12.0 },
    [ 6] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [ 7] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [ 8] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [ 9] = { FRQ = 113.00, RAD =   0, DST =   0.0 },
    [10] = { FRQ = 115.80, RAD = 107, DST =  42.3 },
}

return {
    waypoints = waypoints,
    state = {
        ["active_rnav_edit_segment"] = 3,
        ["active_waypoint"] = {
            ["index"] = 10,
            ["offset_distance_nm"] = 42.299999999999983,
            ["offset_radial_deg"] = 107,
            ["vor_frequency_mhz"] = 115.80000000000001,
        },
        ["current_waypoint_index"] = 10,
        ["selected_heading_bug_deg"] = 244,
        ["selected_offset_distance_nm"] = 42.299999999999983,
        ["selected_offset_radial_deg"] = 107,
        ["selected_vor_course_deg"] = 213,
        ["tuned_ndb_frequency_khz"] = 289,
        ["tuned_vor_frequency_mhz"] = 115.80000000000001,
        ["version"] = 1,
    },
}
