-- SK60 NAV unit persistent memory. Generated by nav_system.lua.
-- This file stores RNAV/NAV programming between DCS sessions.
return {
    ["state"] = {
        ["active_rnav_edit_segment"] = 1,
        ["active_waypoint"] = {
            ["index"] = 1,
            ["offset_distance_nm"] = 60.400000000000006,
            ["offset_radial_deg"] = 187,
            ["vor_frequency_mhz"] = 113,
        },
        ["current_waypoint_index"] = 1,
        ["selected_heading_bug_deg"] = 17,
        ["selected_offset_distance_nm"] = 60.400000000000006,
        ["selected_offset_radial_deg"] = 187,
        ["selected_vor_course_deg"] = 152,
        ["tuned_ndb_frequency_khz"] = 353,
        ["tuned_vor_frequency_mhz"] = 113,
        ["version"] = 1,
        ["waypoint_slots"] = {
            [1] = {
                ["offset_distance_nm"] = 60.400000000000006,
                ["offset_radial_deg"] = 187,
                ["vor_frequency_mhz"] = 113,
            },
            [2] = {
                ["offset_distance_nm"] = 13.4,
                ["offset_radial_deg"] = 156,
                ["vor_frequency_mhz"] = 113,
            },
            [3] = {
                ["offset_distance_nm"] = 10.999999999999996,
                ["offset_radial_deg"] = 100,
                ["vor_frequency_mhz"] = 117,
            },
            [4] = {
                ["offset_distance_nm"] = 15.999999999999996,
                ["offset_radial_deg"] = 233,
                ["vor_frequency_mhz"] = 113.60000000000001,
            },
            [5] = {
                ["offset_distance_nm"] = 0,
                ["offset_radial_deg"] = 0,
                ["vor_frequency_mhz"] = 111.65000000000001,
            },
            [6] = {
                ["offset_distance_nm"] = 0,
                ["offset_radial_deg"] = 0,
                ["vor_frequency_mhz"] = 113,
            },
            [7] = {
                ["offset_distance_nm"] = 0,
                ["offset_radial_deg"] = 0,
                ["vor_frequency_mhz"] = 113,
            },
            [8] = {
                ["offset_distance_nm"] = 0,
                ["offset_radial_deg"] = 0,
                ["vor_frequency_mhz"] = 113,
            },
            [9] = {
                ["offset_distance_nm"] = 0,
                ["offset_radial_deg"] = 0,
                ["vor_frequency_mhz"] = 113,
            },
            [10] = {
                ["offset_distance_nm"] = 0,
                ["offset_radial_deg"] = 0,
                ["vor_frequency_mhz"] = 113,
            },
        },
    },
}
